version: '3.7'
services:
  app:
    build:
      context: ../images/ruby/2.7
    command: /bin/bash -c 'bundle exec rails s -b 0.0.0.0'
    depends_on:
      - ddagent
      - mysql
      - redis
    environment:
      - BUNDLE_GEMFILE=/app/Gemfile
      - DATABASE_URL=mysql2://rails:rails@mysql:3306/rails_dev
      - DATABASE_REPLICA_URL=mysql2://rails_readonly:rails@mysql-replica:3306/rails_dev
      - DD_AGENT_HOST=ddagent
      - DD_HEALTH_METRICS_ENABLED=true
      - DD_METRIC_AGENT_PORT=8125
      - DD_TRACE_AGENT_PORT=8126
      - REDIS_URL=redis://redis:6379
    expose:
      - "3000"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - ../../dd-trace-rb:/vendor/dd-trace-rb
      - ./data/app:/data/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
  ddagent:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_BIND_HOST=0.0.0.0
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_STDOUT=yes
      - DD_PROCESS_AGENT_ENABLED=false
      - LOG_LEVEL=DEBUG
    expose:
      - "8125/udp"
      - "8126"
    volumes:
      - type: bind
        source: ./config/agent.yaml
        target: /etc/datadog-agent/datadog.yaml
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock:ro
      - type: bind
        source: /proc/
        target: /host/proc/:ro
      - type: bind
        source: /sys/fs/cgroup/
        target: /host/sys/fs/cgroup:ro
  mysql:
    image: mysql:8.0
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      - MYSQL_DATABASE=rails_dev
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_PASSWORD=rails
      - MYSQL_USER=rails
    expose:
      - "3306"
  mysql-replica:
    image: mysql:8.0
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      - MYSQL_DATABASE=rails_dev
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_PASSWORD=rails_readonly
      - MYSQL_USER=rails
    expose:
      - "3306"
  redis:
    image: redis:5.0
    expose:
      - "6379"
  loadtester_a:
    build:
      context: ../images/wrk
    command: /bin/bash -c 'bash /app/test.sh'
    depends_on:
      - app
    volumes:
      - ./config/wrk:/app
      - ./data/wrk:/data
volumes:
  bundle:
  node_modules:
