version: '3.2'
services:
  app:
    build:
      context: .
    depends_on:
      - ddagent
    environment:
      - BUNDLE_GEMFILE=/app/Gemfile
      - DD_AGENT_HOST=ddagent
      - DD_SERVICE=acme
      - DD_PROFILING_ENABLED=true
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
  ddagent:
    image: datadog/agent
    environment:
      - DD_APM_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=false
      - DD_BIND_HOST=0.0.0.0
      - DD_API_KEY
      - LOG_LEVEL=DEBUG
    expose:
      - "8125/udp"
      - "8126"
    volumes:
      - ./agent.yaml:/etc/datadog-agent/datadog.yaml
volumes:
  bundle:
