development:
  primary:
    url: <%= ENV['DATABASE_URL'] %>
  primary_replica:
    url: <%= ENV['DATABASE_REPLICA_URL'] %>
    replica: true
test:
  database: rails_test
production:
  database: rails_production
